### ISSUE TITLE
Feature Request: Add Google Recaptcha

### ISSUE THREAD

**Issue by mshoaibdev** [mydnic/laravel-kustomer#51]
Hello,

Thanks for the package.

 It would be great to add Google Recaptcha when submitting the feedback form, to prevent spamming.

**Comment by mydnic** [comment]
Two things come into my mind when I think about this:

First, it's a bit complicated to add reCaptacha in a package like this because reCaptcha comes in various forms (v2, v3, visible with input, visible with badge on the screen, completely invisible).
It would be difficult to support every configuration of Google reCaptcha.

I think a better solution would be to let users override the controller which is used to store the Feedback, so you could add spam protection there.

Second, is this really necessary ? Do bots really submit forms that are not server side rendered ?
